### ISSUE TITLE
grouping entries in the dropdown / in index.tsv

### ISSUE THREAD

**Issue by antonkratz** [Hypercubed/DEIVA#13]
When having a very large number of experiments, i.e. several hundred experiments as we actually have in one project, it becomes difficult to find an experiment in the dropdown menu.

I was wondering whether it's possible to somehow group experiments in the index.tsv file and in the dropdown, for example by LSID, alphabetically, or any other scheme, so that the user can find a specific experiment more quickly.

**Comment by Hypercubed** [comment]
Grouping is possible but would require changing the index file format.  Maybe easier, and more useful, we can replace the drop-down with a ui-select allowing the user to type to filter: http://angular-ui.github.io/ui-select/demo-basic.html

**Comment by Hypercubed** [comment]
Experiment box can now be filtered.
