### ISSUE TITLE
When dropping a data set into the plot area, the title of the scatterplot is still the title of the original example data set

### ISSUE THREAD

**Issue by antonkratz** [Hypercubed/DEIVA#15]
Testing DEIVA v1.0.0-beta.6 under Chrome under OS X.
When I drop a data set into the plot area, the title of the scatterplot is still "Bound vs unbound (DESeq2)", which is the title of the original example data set. I understand that data set which I drop, does not have a title associated with it, because there is no index file. But the title of the plot is now misleading. Suggestion: when dropping a custom data set, erase the title entirely.

**Comment by Hypercubed** [comment]
Fixed... will be in next version.
