### ISSUE TITLE
version in gh-pages branch Zip file is still DEIVA v1.0.0-beta

### ISSUE THREAD

**Issue by antonkratz** [Hypercubed/DEIVA#19]
I went here:
https://github.com/Hypercubed/DEIVA#deploying-deiva-with-your-own-data

and downloaded the "gh-pages branch Zip file" (https://github.com/Hypercubed/DEIVA/archive/gh-pages.zip).

I then realized that the version of DEIVA in that zip-file is still DEIVA v1.0.0-beta.

**Comment by Hypercubed** [comment]
Same as #20 , updated now.
