### ISSUE TITLE
additional column does not show anything in the table

### ISSUE THREAD

**Issue by antonkratz** [Hypercubed/DEIVA#21]
I added one additional column to an input file from the gh-pages branch. The column can be activated by using the drop-down in the upper right corner of the table and is then displayed. However, all fields are empty. The values are not shown.

Tested with Google Chrome (Version 55.0.2883.87 (64-bit) under Xubuntu 16.04.

**Comment by Hypercubed** [comment]
I'm pretty sure this due to the formatting of the header.  What is the column header that you added?

**Comment by antonkratz** [comment]
Example files with additional column added here: https://github.com/antonkratz/DEIVA-tmp/tree/master/data

Live instance of this for testing: https://antonkratz.github.io/DEIVA-tmp/#/

**Comment by Hypercubed** [comment]
Can you verify that this bug does not occur if the extra column header does not contain periods (.).

**Comment by antonkratz** [comment]
Correct! I just tested it.
Does not work: NC.TPM.Mean
Does work: NC_TPM_Mean
So I have a workaround now to display my additional column. But is this behaviour a bug, or a feature? Does it need to be corrected in DEIVA?

**Comment by Hypercubed** [comment]
The `flatEntityAccess` property needs to be set to `true` in the uiGrid options.  PRs welcome.

**Comment by Hypercubed** [comment]
Fixed in v1.0.1
